### ISSUE TITLE
Widget to clear cache from dashboard

### ISSUE THREAD

**Issue by ghost** [vdlp/oc-phast-plugin#1]
Hello,

Nice to see a performance boost plugin for october CMS. Hope I will be able to reduce my TTFB using this cause this is the only indicator that is very high with October (> 800ms) and I never could reduce it (tried memcache, redis, etc... without success).

However, as a cache clear is necessary in order to see changes, it would be great to have a dashboard widget to do that, cause customers for which I'm making website don't even know what is command line and artisan. It would be a nice addition.

Thank you

Alex

**Comment by joris-vdlp** [comment]
Hi Alex!

Thanks for your feedback. 

If you have some spare time left you can always make a pull request for the dashboard widget :) We will put it also on our roadmap. Thanks for thinking along.

**Comment by adrenth** [comment]
Added in version `2.0.0` as of today.
